### PR TITLE
Allow to configure webpack-dev-server

### PR DESCRIPTION
**Pull request by doochik**
I want to configure webpack-dev-server with standard configuration https://webpack.js.org/configuration/dev-server

### CODE REVIEW

**Comment by doochik** [comment]
@ansgarm is it ok? could you merge it?

**Comment by ansgarm** [comment]
Oh, yeah, it is alright 👍

**Comment by ansgarm** [comment]
Published as `5.1.0`

**Comment by doochik** [comment]
thanks!

**Pull request merged**
