### PR TITLE
Fix logging warning event

### PR DESCRIPTION
**Pull request by doochik**

### CODE REVIEW

**Comment by ansgarm** [comment]
Is there more to come or should I release this PR on its own?

**Comment by doochik** [comment]
> Is there more to come or should I release this PR on its own?

Could you release it with this one https://github.com/Hapag-Lloyd/jest-puppeteer-react/pull/56?

**Comment by ansgarm** [comment]
Yes, I can. I had not seen that PR at the time I wrote the comment 😄

**Comment by ansgarm** [comment]
Released as `5.0.2`

**Pull request merged**
